### ISSUE TITLE
obproxy missing a rpm 

### ISSUE THREAD

**Issue by Rhadamanthus00** [oceanbase/obproxy#11]
The  "oceanbase-ce-sql-parser-3.1.0-1.el7.x86_64.rpm" packge is need by obproxy,
however it's missed on the  "https://mirrors.aliyun.com/oceanbase/development-kit/el/7/x86_64".

cat obproxy.el7.x86_64.deps
...
[deps]
devdeps-openssl-static-1.0.1e-3.el7.x86_64.rpm
devdeps-libcurl-static-7.29.0-3.el7.x86_64.rpm
devdeps-mariadb-connector-c-3.1.12-3.el7.x86_64.rpm
devdeps-prometheus-cpp-0.8.0-3.el7.x86_64.rpm
devdeps-gtest-1.8.0-3.el7.x86_64.rpm
devdeps-grpc-1.20.1-3.el7.x86_64.rpm

[tools]
obdevtools-gcc-5.2.0-3.el7.x86_64.rpm
obdevtools-bintuils-2.30-3.el7.x86_64.rpm
obdevtools-bison-2.4.1-3.el7.x86_64.rpm
obdevtools-flex-2.5.35-3.el7.x86_64.rpm

[release]
oceanbase-ce-sql-parser-3.1.0-1.el7.x86_64.rpm <--

**Comment by wgs13579** [comment]
you can find the 'oceanbase-ce-sql-parser-3.1.0-1.el7.x86_64.rpm'  in here：https://mirrors.aliyun.com/oceanbase/community/stable/el/7/x86_64/

**Comment by Rhadamanthus00** [comment]
Thanks.
